from fastapi import APIRouter, UploadFile, File, HTTPException, Form
from v2_model_services.quiz_generation_model import generate_quiz_mistral
from config.db import quizconn
from datetime import datetime
from bson import ObjectId
import os

quiz_model_router = APIRouter()

# --- Upload folder ---
UPLOAD_DIR = "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)

@quiz_model_router.post("/generate-model")
async def generate_quiz_model(
    file: UploadFile = File(...),
    document_type: str = Form("Research Paper"),
    user_id: str = Form("ahsan")
):
    """
    Generate a quiz using Gemini API with RAG.
    Stores the quiz in MongoDB and returns the questions.
    """
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are allowed")
    
    # Save PDF
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    safe_filename = file.filename.replace(" ", "_")
    saved_path = os.path.join(UPLOAD_DIR, f"{timestamp}_v2_quiz_{safe_filename}")
    
    try:
        content = await file.read()
        with open(saved_path, "wb") as f:
            f.write(content)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save PDF: {str(e)}")

    # Generate Quiz
    quiz_data = await generate_quiz_mistral(saved_path, document_type)
    
    if not quiz_data:
        raise HTTPException(status_code=500, detail="Failed to generate quiz content using Gemini API")

    # Store in MongoDB
    quiz_record = {
        "user_id": user_id,
        "document_type": quiz_data.get("document_type", document_type),
        "quiz": quiz_data.get("quiz"),
        "model": "Gemini-2.5-Flash",
        "created_at": datetime.utcnow()
    }
    
    result = quizconn.insert_one(quiz_record)
    quiz_id = str(result.inserted_id)

    # Prepare "clean" quiz for front-end (no solutions)
    full_quiz = quiz_data.get("quiz", {})
    
    return {
        "quiz_id": quiz_id,
        "document_type": quiz_record["document_type"],
        "questions": {
            "mcqs": [
                {
                    "question": m["question"],
                    "options": m["options"],
                    "difficulty": m.get("difficulty", "Medium")
                } for m in full_quiz.get("mcqs", [])
            ],
            "short_answer": [
                {
                    "question": s["question"],
                    "difficulty": s.get("difficulty", "Medium")
                } for s in full_quiz.get("short_answer", [])
            ],
            "true_false": [
                {
                    "statement": t.get("statement", "")
                } for t in full_quiz.get("true_false", [])
            ]
        }
    }

@quiz_model_router.get("/solution/{quiz_id}")
async def get_quiz_solution_model(quiz_id: str):
    """
    Retrieve the solution for a specific quiz generated by the model.
    """
    try:
        quiz = quizconn.find_one({"_id": ObjectId(quiz_id)})
        if not quiz:
            raise HTTPException(status_code=404, detail="Quiz not found")
        
        return {
            "quiz_id": quiz_id,
            "solutions": quiz["quiz"]
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
